package main

func error(a int, b int) {
    Println(a)
    return
}

func main() {
    error(1)
}
